import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
import express from 'express';
import request from 'supertest';

process.env.NODE_ENV='test';
process.env.JWT_SECRET||='x'.repeat(32);process.env.INTEGRATIONS_ENCRYPTION_KEY||='y'.repeat(32);process.env.WORDPRESS_ENCRYPTION_KEY||='z'.repeat(32);
const { account,spend }=await import('../src/server/creditAccounting.ts');
const { creditCatalog }=await import('../src/server/creditCatalog.ts');
const { buildPaystackService }=await import('../src/server/paystackService.ts');
const { buildCreditJobs,acceptPaystackEvent }=await import('../src/server/creditJobs.ts');
const { reserveRefund,applyRefund }=await import('../src/server/creditRefunds.ts');
const { registerCreditStoreRoutes }=await import('../src/server/creditStoreRoutes.ts');

test('Independent credits: PostgreSQL accounting, payments, recharge and refunds',{skip:!process.env.TEST_DATABASE_URL},async t=>{
  const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL});
  const flags=['CREDITS_RECHARGE_LIVE_ENABLED','CREDITS_RECHARGE_TEST_ENABLED','CREDITS_REFUNDS_LIVE_ENABLED','CREDITS_REFUNDS_TEST_ENABLED'];
  const originals=flags.map(key=>process.env[key]);flags.forEach(key=>process.env[key]='true');
  try {
    await (await import('../src/db-migrations.ts')).runDatabaseMigrations(pool);
    await (await import('../src/payment-migrations.ts')).runPaymentMigrations(pool);
    async function fixture(mode:'live'|'test'='live',role=mode==='test'?'admin':'user',allowance=0) {
      const userId=randomUUID();const email=`${userId}@example.com`;
      await pool.query("INSERT INTO users(id,email,password_hash,role,status) VALUES($1,$2,'fixture',$3,'active')",[userId,email,role]);
      await account(pool,userId,allowance,mode);
      let saved={mode,testSecretKey:'sk_test_fixture',liveSecretKey:'sk_live_fixture',currency:'GHS',fxRate:'15'};
      const initialized=new Map<string,any>();const refunds=new Map<string,any[]>();let postCount=0;let chargeBehavior='success';let chargeCount=0;
      const http={post:async(url:string,body:any)=>{
        postCount++;
        if(url.endsWith('/refund')) {refunds.set(String(body.transaction),[{id:randomUUID(),transaction:body.transaction,domain:mode,currency:body.currency,amount:body.amount,status:'pending'}]);return {data:{status:true,data:{id:refunds.get(String(body.transaction))![0].id,status:'pending'}}};}
        initialized.set(body.reference,body);
        if(url.endsWith('charge_authorization')) {chargeCount++;if(chargeBehavior==='timeout')throw new Error('Timeout');return {data:{status:true,data:{status:chargeBehavior==='decline'?'failed':'success'}}};}
        return {data:{status:true,data:{reference:body.reference,authorization_url:`https://checkout.paystack.com/${body.reference}`}}};
      },get:async(url:string,options?:any)=>{
        if(url.endsWith('/refund'))return {data:{status:true,data:refunds.get(String(options.params.transaction))||[]}};
        const reference=decodeURIComponent(url.split('/').at(-1)!);let body=initialized.get(reference);
        if(!body)body=(await pool.query('SELECT amount_subunits AS amount,currency,customer_email AS email FROM paystack_orders WHERE reference=$1',[reference])).rows[0];
        if(!body)throw new Error('Unknown fixture');
        return {data:{status:true,data:{id:reference,reference,domain:mode,amount:body.amount,currency:body.currency,status:'success',paid_at:new Date().toISOString(),customer:{email:body.email},authorization:{authorization_code:'AUTH_fixture',signature:`SIG_${userId}`,reusable:true,card_type:'visa',last4:'4081',exp_month:'12',exp_year:'2099'}}}};
      }};
      const read=async()=>saved;const service=buildPaystackService({pool,readConfig:read,http:http as any});const jobs=buildCreditJobs(pool,read,http as any);
      const app=express();app.use(express.json());app.use(registerCreditStoreRoutes({pool,getPlatformConfig:read,http:http as any,hasDatabase:()=>true,requireAuth:()=>({userId,role}),requireAdmin:async(_req,res)=>role==='admin'?{userId,role}:(res.status(403).json({success:false,error:'Administrator required'}),null)}));
      async function buy(id='starter',saveCard=false) {const catalog=await creditCatalog(pool,read);const order=await service.checkout(userId,'credits',id,{catalogVersion:catalog.version,saveCard});await service.verify(order.reference,userId);return order;}
      async function enable(threshold=50,monthlyLimit=3) {const method=(await pool.query('SELECT id FROM credit_payment_methods WHERE user_id=$1',[userId])).rows[0];const catalog=await creditCatalog(pool,read);const response=await request(app).put('/credits/auto-recharge').send({enabled:true,packId:'starter',methodId:method.id,threshold,monthlyLimit,catalogVersion:catalog.version,consent:true});assert.equal(response.status,200,response.text);}
      return {userId,email,app,buy,enable,service,jobs,read,http,refunds,setCharge:(value:string)=>{chargeBehavior=value;},setFx:(value:string)=>{saved={...saved,fxRate:value};},setMode:(value:'live'|'test')=>{saved={...saved,mode:value};},charges:()=>chargeCount,posts:()=>postCount};
    }
    await t.test('four packs have agreed quantities and server-owned prices',async()=>{const f=await fixture();const catalog=await creditCatalog(pool,f.read);assert.deepEqual(catalog.packs.map(p=>[p.id,p.credits,p.priceUsd]),[['mini',250,3],['starter',1000,12],['growth',5000,49],['power',20000,149]]);assert.equal(catalog.packs[0].amount,45);});
    await t.test('Free users purchase independently; no subscription or plan is granted',async()=>{const f=await fixture();await f.buy('mini');assert.equal((await pool.query('SELECT * FROM subscriptions WHERE user_id=$1',[f.userId])).rowCount,0);assert.equal((await pool.query('SELECT plan_id FROM users WHERE id=$1',[f.userId])).rows[0].plan_id,null);assert.equal((await account(pool,f.userId,100)).purchasedCredits,250);});
    await t.test('monthly allowance first, FIFO lots, accurate reset delta, purchased rollover',async()=>{const f=await fixture('live','user',100);await account(pool,f.userId,100);const first=await f.buy('mini');await f.buy('starter');await spend(pool,f.userId,200,'usage');const lots=(await pool.query('SELECT order_reference,remaining FROM credit_lots WHERE user_id=$1 ORDER BY created_at,id',[f.userId])).rows;assert.equal(lots.find(l=>l.order_reference===first.reference).remaining,150);await pool.query("UPDATE user_credits SET reset_date=NOW()-INTERVAL '1 day' WHERE user_id=$1",[f.userId]);const after=await account(pool,f.userId,100);assert.equal(after.credits,1250);assert.equal(after.purchasedCredits,1150);assert.equal((await pool.query("SELECT delta FROM credit_events WHERE user_id=$1 AND reason='monthly_reset'",[f.userId])).rows[0].delta,100);});
    await t.test('concurrent spending never produces negative balance or overspends lots',async()=>{const f=await fixture();await f.buy('mini');const results=await Promise.allSettled([spend(pool,f.userId,200,'usage'),spend(pool,f.userId,200,'usage')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await account(pool,f.userId,0)).purchasedCredits,50);});
    await t.test('route rejects missing key, missing pack, client prices, stale quote and foreign receipt',async()=>{const f=await fixture();assert.equal((await request(f.app).post('/credits/purchase').send({packId:'mini'})).status,400);const catalog=await creditCatalog(pool,f.read);for(const body of [{catalogVersion:catalog.version},{packId:'mini',catalogVersion:catalog.version,amount:1},{packId:'missing',catalogVersion:catalog.version}])assert.ok((await request(f.app).post('/credits/purchase').set('Idempotency-Key',randomUUID()).send(body)).status>=400);assert.equal((await request(f.app).post('/credits/purchase').set('Idempotency-Key',randomUUID()).send({packId:'mini',catalogVersion:'old'})).status,409);const other=await fixture();const order=await other.buy();assert.equal((await request(f.app).get(`/credits/receipts/${order.reference}`)).status,404);assert.equal(f.posts(),0);});
    await t.test('disabled account cannot initialize a purchase',async()=>{const f=await fixture();await pool.query("UPDATE users SET status='suspended' WHERE id=$1",[f.userId]);await assert.rejects(f.buy(),/not active/);assert.equal(f.posts(),0);});
    await t.test('agency alias buys Power without rewriting historical references',async()=>{const f=await fixture();const order=await f.buy('agency');assert.equal((await pool.query('SELECT pack_id,credits FROM paystack_orders WHERE reference=$1',[order.reference])).rows[0].pack_id,'power');});
    await t.test('concurrent verification yields exactly one lot and receipt',async()=>{const f=await fixture();const order=await f.service.checkout(f.userId,'credits','mini');await Promise.all([f.service.verify(order.reference),f.service.verify(order.reference)]);assert.equal((await pool.query('SELECT * FROM credit_lots WHERE order_reference=$1',[order.reference])).rowCount,1);assert.equal((await pool.query('SELECT * FROM billing_invoices WHERE paystack_reference=$1',[order.reference])).rowCount,1);});
    await t.test('reusable cards saved only with consent and secrets never exposed',async()=>{const f=await fixture();await f.buy();assert.equal((await request(f.app).get('/credits/payment-methods')).body.methods.length,0);await f.buy('starter',true);const result=await request(f.app).get('/credits/payment-methods');assert.equal(result.body.methods[0].last4,'4081');assert.ok(!result.text.includes('AUTH_fixture'));const stored=(await pool.query('SELECT authorization_encrypted FROM credit_payment_methods WHERE user_id=$1',[f.userId])).rows[0];assert.ok(!stored.authorization_encrypted.includes('AUTH_fixture'));});
    await t.test('recharge requires explicit consent and an owned reusable card',async()=>{const f=await fixture();await f.buy('starter',true);const catalog=await creditCatalog(pool,f.read);assert.equal((await request(f.app).put('/credits/auto-recharge').send({enabled:true,packId:'starter',catalogVersion:catalog.version})).status,409);assert.equal((await request(f.app).put('/credits/auto-recharge').send({enabled:true,packId:'starter',methodId:'foreign',catalogVersion:catalog.version,consent:true})).status,400);});
    await t.test('recharge sweep, single concurrent charge and cooldown',async()=>{const f=await fixture();await f.buy('starter',true);await f.enable();await spend(pool,f.userId,1000,'usage');await Promise.all([f.jobs.recharge(),f.jobs.recharge()]);assert.equal(f.charges(),1);await spend(pool,f.userId,1000,'usage');await f.jobs.sweep();await f.jobs.recharge();assert.equal(f.charges(),1);});
    await t.test('monthly limit blocks additional charges after cooldown',async()=>{const f=await fixture();await f.buy('starter',true);await f.enable(50,1);await spend(pool,f.userId,1000,'usage');await f.jobs.recharge();await pool.query("UPDATE credit_recharge_jobs SET submitted_at=NOW()-INTERVAL '25 hours' WHERE user_id=$1",[f.userId]);await spend(pool,f.userId,1000,'usage');await f.jobs.recharge();assert.equal(f.charges(),1);});
    await t.test('timeout reconciles original reference without a second charge',async()=>{const f=await fixture();await f.buy('starter',true);await f.enable();f.setCharge('timeout');await spend(pool,f.userId,1000,'usage');await f.jobs.recharge();assert.equal(f.charges(),1);const job=(await pool.query("SELECT * FROM credit_recharge_jobs WHERE user_id=$1",[f.userId])).rows[0];assert.equal(job.status,'unknown');await pool.query("UPDATE paystack_orders SET created_at=NOW()-INTERVAL '2 minutes' WHERE reference=$1",[job.order_reference]);await f.jobs.reconcile();await f.jobs.recharge();assert.equal(f.charges(),1);assert.equal((await pool.query('SELECT status FROM credit_recharge_jobs WHERE id=$1',[job.id])).rows[0].status,'successful');});
    await t.test('declines pause recharge and notify user',async()=>{const f=await fixture();await f.buy('starter',true);await f.enable();f.setCharge('decline');await spend(pool,f.userId,1000,'usage');await f.jobs.recharge();assert.equal((await pool.query('SELECT enabled FROM credit_recharge_agreements WHERE user_id=$1',[f.userId])).rows[0].enabled,false);assert.equal((await pool.query("SELECT * FROM notifications WHERE user_id=$1 AND title='Automatic recharge paused'",[f.userId])).rowCount,1);});
    await t.test('disabling recharge or removing card prevents new charge',async()=>{const f=await fixture();await f.buy('starter',true);await f.enable();await spend(pool,f.userId,1000,'usage');await request(f.app).put('/credits/auto-recharge').send({enabled:false});await f.jobs.recharge();assert.equal(f.charges(),0);await f.enable();const method=(await request(f.app).get('/credits/payment-methods')).body.methods[0];await request(f.app).delete(`/credits/payment-methods/${method.id}`);await f.jobs.sweep();await f.jobs.recharge();assert.equal(f.charges(),0);});
    await t.test('FX change pauses recharge before provider call',async()=>{const f=await fixture();await f.buy('starter',true);await f.enable();await spend(pool,f.userId,1000,'usage');f.setFx('16');await f.jobs.recharge();assert.equal(f.charges(),0);assert.equal((await pool.query('SELECT enabled FROM credit_recharge_agreements WHERE user_id=$1',[f.userId])).rows[0].enabled,false);});
    await t.test('refund reservation excludes credits from spending; failed refund releases',async()=>{const f=await fixture();const order=await f.buy('mini');await reserveRefund(pool,order.reference,f.userId,'Test refund');assert.equal((await account(pool,f.userId,0)).credits,0);await assert.rejects(spend(pool,f.userId,1,'usage'),/Insufficient/);await applyRefund(pool,order.reference,'live','failed','refund-id');assert.equal((await account(pool,f.userId,0)).credits,250);});
    await t.test('processed refund reverses once, writes ledger and receipt status',async()=>{const f=await fixture();const order=await f.buy('mini');await reserveRefund(pool,order.reference,f.userId,'Test refund');await applyRefund(pool,order.reference,'live','processed','refund-id');await applyRefund(pool,order.reference,'live','processed','refund-id');const balance=await account(pool,f.userId,0);assert.equal(balance.purchasedCredits,0);assert.equal(balance.reservedCredits,0);assert.equal((await pool.query("SELECT * FROM credit_events WHERE user_id=$1 AND reason='refund_processed'",[f.userId])).rowCount,1);assert.equal((await pool.query('SELECT status FROM billing_invoices WHERE paystack_reference=$1',[order.reference])).rows[0].status,'refunded');});
    await t.test('used purchase refund rejected; concurrent refund/spend cannot both win',async()=>{const f=await fixture();const order=await f.buy('mini');const results=await Promise.allSettled([spend(pool,f.userId,1,'usage'),reserveRefund(pool,order.reference,f.userId,'Test refund')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
    await t.test('external reversal of spent credits freezes account without negative balance',async()=>{const f=await fixture();const order=await f.buy('mini');await spend(pool,f.userId,200,'usage');await applyRefund(pool,order.reference,'live','processed','external',true);const balance=await account(pool,f.userId,0);assert.equal(balance.totalCredits,50);assert.equal(balance.spendingBlocked,true);await assert.rejects(spend(pool,f.userId,1,'usage'),/review/);});
    await t.test('test purchase, authorization and refund never mutate live balances',async()=>{const f=await fixture('test');const order=await f.buy('mini',true);assert.equal((await pool.query('SELECT * FROM user_credits WHERE user_id=$1',[f.userId])).rowCount,0);await reserveRefund(pool,order.reference,f.userId,'Sandbox refund');await applyRefund(pool,order.reference,'test','processed','sandbox');assert.equal((await pool.query('SELECT * FROM billing_invoices WHERE user_id=$1',[f.userId])).rowCount,0);assert.equal((await pool.query('SELECT credits FROM paystack_sandbox_accounts WHERE user_id=$1',[f.userId])).rows[0].credits,0);assert.equal((await pool.query("SELECT * FROM credit_payment_methods WHERE user_id=$1 AND mode='live'",[f.userId])).rowCount,0);});
    await t.test('webhook inbox deduplicates exact events before processing',async()=>{const f=await fixture();const order=await f.service.checkout(f.userId,'credits','mini');const payload={event:'charge.success',data:{reference:order.reference}};const raw=Buffer.from(JSON.stringify(payload));await acceptPaystackEvent(pool,'live',raw,payload);await acceptPaystackEvent(pool,'live',raw,payload);assert.equal((await pool.query("SELECT * FROM paystack_event_inbox WHERE payload->'data'->>'reference'=$1",[order.reference])).rowCount,1);await f.jobs.events();assert.equal((await account(pool,f.userId,0)).purchasedCredits,250);});
    await t.test('first purchase preserves initial Free allowance',async()=>{const f=await fixture();await pool.query('DELETE FROM user_credits WHERE user_id=$1',[f.userId]);await f.buy('mini');const balance=await account(pool,f.userId,100);assert.equal(balance.allowanceRemaining,100);assert.equal(balance.credits,350);});
    await t.test('plan downgrade/reset preserves purchased credits and logs actual negative delta',async()=>{const f=await fixture('live','user',2000);await f.buy('mini');await pool.query("UPDATE user_credits SET reset_date=NOW()-INTERVAL '1 day' WHERE user_id=$1",[f.userId]);const balance=await account(pool,f.userId,100);assert.equal(balance.purchasedCredits,250);assert.equal(balance.credits,350);assert.equal((await pool.query("SELECT delta FROM credit_events WHERE user_id=$1 AND reason='monthly_reset'",[f.userId])).rows[0].delta,-1900);});
    await t.test('refund lot cannot be spent while other purchased lots remain usable',async()=>{const f=await fixture();const first=await f.buy('mini');await f.buy('starter');await reserveRefund(pool,first.reference,f.userId,'Refund unused purchase');await spend(pool,f.userId,1000,'usage');assert.equal((await pool.query('SELECT remaining FROM credit_lots WHERE order_reference=$1',[first.reference])).rows[0].remaining,250);await applyRefund(pool,first.reference,'live','processed','refund-other');assert.equal((await account(pool,f.userId,0)).credits,0);});
    await t.test('expired card pauses recharge without charge',async()=>{const f=await fixture();await f.buy('starter',true);await f.enable();await pool.query("UPDATE credit_payment_methods SET exp_year='2020' WHERE user_id=$1",[f.userId]);await spend(pool,f.userId,1000,'usage');await f.jobs.recharge();assert.equal(f.charges(),0);assert.equal((await pool.query('SELECT enabled FROM credit_recharge_agreements WHERE user_id=$1',[f.userId])).rows[0].enabled,false);});
    await t.test('non-reusable channel cannot save payment method',async()=>{const f=await fixture();const original=f.http.get;f.http.get=async(...args:any[])=>{const result=await (original as any)(...args);if(result.data.data?.authorization)result.data.data.authorization.reusable=false;return result;};await f.buy('mini',true);assert.equal((await request(f.app).get('/credits/payment-methods')).body.methods.length,0);});
    await t.test('recharge retains original authorization email after account email changes',async()=>{const f=await fixture();await f.buy('starter',true);await f.enable();await pool.query('UPDATE users SET email=$2 WHERE id=$1',[f.userId,`${randomUUID()}@example.com`]);await spend(pool,f.userId,1000,'usage');await f.jobs.recharge();const order=(await pool.query("SELECT customer_email FROM paystack_orders WHERE user_id=$1 AND purchase_source='recharge'",[f.userId])).rows[0];assert.equal(order.customer_email,f.email);assert.equal(f.charges(),1);});
    await t.test('admin refunds submit once and remain pending until provider confirmation',async()=>{const f=await fixture('live','admin');const order=await f.buy('mini');const result=await request(f.app).post(`/admin/credit-purchases/${order.reference}/refund`).send({reason:'Customer requested unused purchase refund'});assert.equal(result.status,202,result.text);assert.equal(result.body.refund.status,'pending');await f.jobs.submitRefund(order.reference);assert.equal(f.posts(),2);const providerId=(await pool.query('SELECT provider_transaction_id FROM paystack_orders WHERE reference=$1',[order.reference])).rows[0].provider_transaction_id;f.refunds.get(providerId)![0].status='processed';await f.jobs.reconcileRefund(order.reference,'live');assert.equal((await account(pool,f.userId,0)).purchasedCredits,0);});
    await t.test('pack edits pause affected recharge and preserve stored order quantities/prices',async()=>{const f=await fixture();await f.buy('starter',true);await f.enable();const admin=await fixture('live','admin');const oldOrder=await f.service.checkout(f.userId,'credits','starter');const pack=(await creditCatalog(pool,admin.read)).packs.find(p=>p.id==='starter')!;const body={id:pack.id,name:pack.name,description:pack.description,credits:1100,priceUsd:13,displayOrder:pack.displayOrder,active:true};try{assert.equal((await request(admin.app).put('/admin/credit-packs/starter').send(body)).status,200);assert.equal((await pool.query('SELECT enabled FROM credit_recharge_agreements WHERE user_id=$1',[f.userId])).rows[0].enabled,false);await f.service.verify(oldOrder.reference);const order=(await pool.query('SELECT credits,amount_subunits FROM paystack_orders WHERE reference=$1',[oldOrder.reference])).rows[0];assert.equal(order.credits,1000);assert.equal(order.amount_subunits,18000);}finally{await request(admin.app).put('/admin/credit-packs/starter').send({...body,credits:1000,priceUsd:12});}});
    await t.test('administrator resolves processed external refund by writing off only remaining credits',async()=>{const f=await fixture('live','admin');const order=await f.buy('mini');await spend(pool,f.userId,200,'usage');await applyRefund(pool,order.reference,'live','processed','external',true);const incident=(await pool.query('SELECT * FROM credit_incidents WHERE reference=$1',[order.reference])).rows[0];assert.equal((await request(f.app).post(`/admin/credits/incidents/${incident.id}/resolve`).send({action:'write_off',reason:'Provider refund confirmed; waive consumed credits'})).status,200);const balance=await account(pool,f.userId,0);assert.equal(balance.credits,0);assert.equal(balance.purchasedCredits,0);assert.equal(balance.spendingBlocked,false);});
    await t.test('mode switch invalidates quote before checkout initialization',async()=>{const f=await fixture('live','admin');const catalog=await creditCatalog(pool,f.read);f.setMode('test');await assert.rejects(f.service.checkout(f.userId,'credits','mini',{catalogVersion:catalog.version}),(error:any)=>error.status===409);assert.equal(f.posts(),0);});
    await t.test('mode switch prevents automatic live charges',async()=>{const f=await fixture('live','admin');await f.buy('starter',true);await f.enable();await spend(pool,f.userId,1000,'usage');f.setMode('test');await f.jobs.recharge();assert.equal(f.charges(),0);});
    await t.test('administrator edits persist and are audited, user cannot edit',async()=>{const f=await fixture('live','admin');const body={id:`test-${randomUUID().slice(0,20)}`,name:'Test pack',description:'Testing',credits:300,priceUsd:4,displayOrder:20,active:true};assert.equal((await request(f.app).post('/admin/credit-packs').send(body)).status,200);assert.equal((await request(f.app).put(`/admin/credit-packs/${body.id}`).send({...body,active:false})).status,200);assert.equal((await pool.query("SELECT * FROM audit_logs WHERE user_id=$1 AND action='admin_credit_pack_updated'",[f.userId])).rowCount,2);const other=await fixture();assert.equal((await request(other.app).post('/admin/credit-packs').send(body)).status,403);});
  } finally {
    flags.forEach((key,index)=>originals[index]===undefined?delete process.env[key]:process.env[key]=originals[index]);await pool.end();
  }
});
