import { useEffect, useState } from 'react';
import { creditRequest, money, type CreditPack } from '../../services/creditService';

const field='mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm focus-visible:outline-2 focus-visible:outline-indigo-600';
const control='rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold hover:bg-slate-50 disabled:opacity-50';
const empty={id:'',name:'',description:'',credits:250,priceUsd:3,displayOrder:4,active:true};
interface AdminPurchase { reference:string;customer_email:string;pack_name:string;credits:number;remaining:number;reserved:boolean;legacy:boolean;amount_subunits:number;currency:string;status:string;refund_status:string|null;fulfilled_at:string|null }
export default function CreditManagement() {
  const [packs,setPacks]=useState<CreditPack[]>([]);const [purchases,setPurchases]=useState<AdminPurchase[]>([]);const [mode,setMode]=useState<'test'|'live'>('test');
  const [draft,setDraft]=useState(empty);const [editing,setEditing]=useState(false);const [formOpen,setFormOpen]=useState(false);
  const [refundReference,setRefundReference]=useState('');const [reason,setReason]=useState('');const [refundsAvailable,setRefundsAvailable]=useState(false);
  const [metrics,setMetrics]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  const [incidents,setIncidents]=useState<{id:string;user_id:string;reference:string|null;mode:string;reason:string}[]>([]);
  const [incidentId,setIncidentId]=useState('');const [resolution,setResolution]=useState('unblock');const [resolutionReason,setResolutionReason]=useState('');
  async function load() {
    const [catalog,orders,monitoring]=await Promise.all([creditRequest<{packs:CreditPack[]}>('/admin/credit-packs'),creditRequest<{items:AdminPurchase[];refundsAvailable:boolean}>(`/admin/credit-purchases?mode=${mode}`),creditRequest<{metrics:Record<string,string>;incidents:typeof incidents}>('/admin/credits/monitoring')]);
    setPacks(catalog.packs);setPurchases(orders.items);setRefundsAvailable(orders.refundsAvailable);setMetrics(monitoring.metrics);
    setIncidents(monitoring.incidents||[]);
  }
  useEffect(()=>{void load().catch(e=>setError(e.message));},[mode]);
  async function action(fn:()=>Promise<void>) {if(busy)return;setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e instanceof Error?e.message:'Operation failed');}finally{setBusy(false);}}
  return <section className="space-y-6 rounded-xl border border-slate-200 bg-white p-5 sm:p-6" aria-labelledby="credit-management">
    <header className="flex flex-wrap justify-between gap-3"><div><h2 id="credit-management" className="text-lg font-semibold">Credit packs and refunds</h2><p className="mt-1 text-sm text-slate-500">Pricing changes preserve existing orders and require renewed recharge consent.</p></div><button className={control} onClick={()=>{setDraft(empty);setEditing(false);setFormOpen(true);}}>Create pack</button></header>
    {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{message&&<p role="status" className="text-sm text-emerald-700">{message}</p>}
    <div className="divide-y divide-slate-100">{packs.map(pack=><div key={pack.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{pack.name} {!pack.active&&<span className="text-sm text-slate-500">(Disabled)</span>}</p><p className="text-sm text-slate-500">{pack.credits.toLocaleString()} credits · {money(pack.priceUsd,'USD')} list price · position {pack.displayOrder}</p></div><button className={control} onClick={()=>{setDraft({id:pack.id,name:pack.name,description:pack.description,credits:pack.credits,priceUsd:pack.priceUsd,displayOrder:pack.displayOrder,active:pack.active});setEditing(true);setFormOpen(true);}}>Edit {pack.name}</button></div>)}</div>
    {formOpen&&<form className="space-y-4 border-y border-slate-200 py-5" onSubmit={e=>{e.preventDefault();void action(async()=>{await creditRequest(editing?`/admin/credit-packs/${draft.id}`:'/admin/credit-packs',editing?'PUT':'POST',draft);setFormOpen(false);setMessage('Credit pack saved.');});}}><h3 className="font-semibold">{editing?'Edit pack':'New pack'}</h3><div className="grid gap-4 sm:grid-cols-2">
      <label className="text-sm">Pack ID<input className={field} value={draft.id} disabled={editing} required pattern="[a-z][a-z0-9-]*" onChange={e=>setDraft({...draft,id:e.target.value})}/></label>
      <label className="text-sm">Name<input className={field} value={draft.name} required maxLength={80} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
      <label className="text-sm">Credits<input className={field} type="number" min={1} max={1000000} required value={draft.credits} onChange={e=>setDraft({...draft,credits:Number(e.target.value)})}/></label>
      <label className="text-sm">USD list price<input className={field} type="number" min={0.01} max={10000} step="0.01" required value={draft.priceUsd} onChange={e=>setDraft({...draft,priceUsd:Number(e.target.value)})}/></label>
      <label className="text-sm">Display order<input className={field} type="number" min={0} max={1000} required value={draft.displayOrder} onChange={e=>setDraft({...draft,displayOrder:Number(e.target.value)})}/></label>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>Available for purchase</label>
    </div><label className="block text-sm">Description<textarea className={field} maxLength={300} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="flex gap-3"><button type="submit" disabled={busy} className={control}>Save pack</button><button type="button" className={control} onClick={()=>setFormOpen(false)}>Cancel</button></div></form>}
    <div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Credit purchases</h3><label className="text-sm">Payment mode <select className="ml-2 rounded-lg border border-slate-300 p-2" value={mode} onChange={e=>{setMode(e.target.value as 'test'|'live');setRefundReference('');}}><option value="test">Test</option><option value="live">Live</option></select></label></div>
    {!refundsAvailable&&<p className="text-sm text-slate-500">Refund initiation is disabled for this mode. Existing refunds continue to reconcile.</p>}
    {!purchases.length&&<p className="text-sm text-slate-500">No credit purchases in this mode.</p>}
    <div className="divide-y divide-slate-100">{purchases.map(p=><div key={p.reference} className="flex flex-wrap items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="break-all text-sm font-medium">{p.customer_email} · {p.pack_name||'Credit purchase'}</p><p className="text-sm text-slate-500">{money(p.amount_subunits/100,p.currency)} · {p.refund_status?`Refund ${p.refund_status}`:p.status} · {p.remaining??0}/{p.credits} unused</p><p className="break-all text-xs text-slate-400">{p.reference}</p></div>{p.fulfilled_at&&!p.refund_status&&!p.legacy&&!p.reserved&&p.remaining===p.credits&&<button className={control} disabled={!refundsAvailable||busy} onClick={()=>{setRefundReference(p.reference);setReason('');}}>Request full refund</button>}</div>)}</div>
    {refundReference&&<form className="space-y-3 rounded-xl border border-amber-200 bg-amber-50 p-4" onSubmit={e=>{e.preventDefault();void action(async()=>{await creditRequest(`/admin/credit-purchases/${encodeURIComponent(refundReference)}/refund`,'POST',{reason},crypto.randomUUID());setRefundReference('');setMessage('Refund requested. Credits are reserved until Paystack confirms the outcome.');});}}><p className="break-all text-sm font-medium">Refund entire payment: {refundReference}</p><p className="text-sm text-amber-900">Only completely unused purchases are eligible. Submitted refunds cannot be cancelled here.</p><label className="block text-sm">Audit reason<input className={field} value={reason} minLength={3} maxLength={300} required onChange={e=>setReason(e.target.value)}/></label><div className="flex gap-3"><button className={control} type="submit" disabled={busy}>Submit full refund</button><button className={control} type="button" onClick={()=>setRefundReference('')}>Cancel</button></div></form>}
    <details className="border-t border-slate-200 pt-4"><summary className="cursor-pointer text-sm font-semibold">Credit operations monitoring</summary><dl className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(metrics).map(([name,count])=><div key={name} className="flex justify-between text-sm"><dt className="capitalize text-slate-500">{name.replace(/_/g,' ')}</dt><dd className="tabular-nums">{count}</dd></div>)}</dl></details>
    {incidents.length>0&&<div className="space-y-3 border-t border-slate-200 pt-4"><h3 className="font-semibold">Accounts requiring review</h3>{incidents.map(i=><div key={i.id} className="flex flex-wrap justify-between gap-3 text-sm"><div className="min-w-0"><p>{i.reason} · {i.mode}</p><p className="break-all text-slate-500">Account {i.user_id}{i.reference?` · ${i.reference}`:''}</p></div><button className={control} onClick={()=>{setIncidentId(i.id);setResolutionReason('');}}>Review incident</button></div>)}</div>}
    {incidentId&&<form className="space-y-3 border-t border-slate-200 pt-4" onSubmit={e=>{e.preventDefault();void action(async()=>{await creditRequest(`/admin/credits/incidents/${incidentId}/resolve`,'POST',{action:resolution,reason:resolutionReason});setIncidentId('');setMessage('Incident reconciled and audited.');});}}><h3 className="font-semibold">Reconcile account</h3><p className="text-sm text-slate-500">Unblocking requires a reconciled balance and a failed provider reversal. Write-off requires a confirmed processed external refund and removes only remaining credits.</p><label className="block text-sm">Resolution<select className={field} value={resolution} onChange={e=>setResolution(e.target.value)}><option value="unblock">Unblock reconciled account</option><option value="write_off">Write off remaining refunded credits</option></select></label><label className="block text-sm">Resolution audit reason<input className={field} required minLength={5} maxLength={300} value={resolutionReason} onChange={e=>setResolutionReason(e.target.value)}/></label><div className="flex gap-3"><button className={control} disabled={busy} type="submit">Resolve incident</button><button className={control} type="button" onClick={()=>setIncidentId('')}>Cancel</button></div></form>}
  </section>;
}
